In [4]:
columns = ["No.", "mat", "r(A)", "R", "G", "B"]
df_elm = pd.DataFrame(columns=columns)

In [7]:
df_elm.loc[0, "No."] = 1
df_elm.loc[0, "mat"] = 2
df_elm.loc[0, "r(A)"] = 3
df_elm.loc[0, "R"] = 4
df_elm.loc[0, "G"] = 5
df_elm.loc[0, "B"] = 6

In [8]:
df_elm

   No.  mat  r(A)  R  G  B
0    1    2     3  4  5  6

In [24]:
import pandas as pd

columns = ["No.", "mat", "R_atomic(A)", "R_ionic(A)", "R_Waals(A)", "R", "G", "B"]
df_elm = pd.DataFrame(columns=columns)

line = " "
with open("elements.ini", "r") as f:
    idx = 0
    while line:
        line = f.readline()
        if not line:
            break
            
        data = line.rstrip("\n").rstrip("\r").lstrip(" ").split()
        df_elm.loc[idx] = data
        idx += 1
    
df_elm["No."] = df_elm["No."].astype("int")
df_elm.iloc[:, 2:] = df_elm.iloc[:, 2:].astype("float")
df_elm.to_csv("VESTA_elements.csv", index=False)

In [31]:
df_elm.head(10)

   No. mat  R_atomic(A)  R_ionic(A)  R_Waals(A)        R        G        B
0    1   H         0.46        1.20        0.20  1.00000  0.80000  0.80000
1    1   D         0.46        1.20        0.20  0.80000  0.80000  1.00000
2    2  He         1.22        1.40        1.22  0.98907  0.91312  0.81091
3    3  Li         1.57        1.40        0.59  0.52731  0.87953  0.45670
4    4  Be         1.12        1.40        0.27  0.37147  0.84590  0.48292
5    5   B         0.81        1.40        0.11  0.12490  0.63612  0.05948
6    6   C         0.77        1.70        0.15  0.50430  0.28659  0.16236
7    7   N         0.74        1.55        1.46  0.69139  0.72934  0.90280
8    8   O         0.74        1.52        1.40  0.99997  0.01328  0.00000
9    9   F         0.72        1.47        1.33  0.69139  0.72934  0.90280

In [37]:
mat_annot = {}

line = " "
with open("materials_list.txt", "r") as f:
    idx = 0
    while line:
        line = f.readline()
        if not line:
            break
            
        data = line.rstrip("\n").rstrip("\r").lstrip(" ").replace("-", "").split()
        print data[0], data[1]
        mat_annot.update({data[0]: data[1]})
        idx += 1

mat_annot

H Hydrogen
He Helium
Li Lithium
Be Beryllium
B Boron
C Carbon
N Nitrogen
O Oxygen
F Fluorine
Ne Neon
Na Sodium
Mg Magnesium
Al Aluminum,
Si Silicon
P Phosphorus
S Sulfur
Cl Chlorine
Ar Argon
K Potassium
Ca Calcium
Sc Scandium
Ti Titanium
V Vanadium
Cr Chromium
Mn Manganese
Fe Iron
Co Cobalt
Ni Nickel
Cu Copper
Zn Zinc
Ga Gallium
Ge Germanium
As Arsenic
Se Selenium
Br Bromine
Kr Krypton
Rb Rubidium
Sr Strontium
Y Yttrium
Zr Zirconium
Nb Niobium
Mo Molybdenum
Tc Technetium
Ru Ruthenium
Rh Rhodium
Pd Palladium
Ag Silver
Cd Cadmium
In Indium
Sn Tin
Sb Antimony
Te Tellurium
I Iodine
Xe Xenon
Cs Cesium
Ba Barium
La Lanthanum
Ce Cerium
Pr Praseodymium
Nd Neodymium
Pm Promethium
Sm Samarium
Eu Europium
Gd Gadolinium
Tb Terbium
Dy Dysprosium
Ho Holmium
Er Erbium
Tm Thulium
Yb Ytterbium
Lu Lutetium
Hf Hafnium
Ta Tantalum
W Tungsten
Re Rhenium
Os Osmium
Ir Iridium
Pt Platinum
Au Gold
Hg Mercury
Tl Thallium
Pb Lead
Bi Bismuth
Po Polonium
At Astatine
Rn Radon
Fr Francium
Ra Radium
Ac Actinium
Th Thorium
Pa Protactinium
U Uranium
Np Neptunium
Pu Plutonium
Am Americium
Cm Curium
Bk Berkelium
Cf Californium
Es Einsteinium
Fm Fermium
Md Mendelevium
No Nobelium
Lr Lawrencium
Rf Rutherfordium
Db Dubnium
Sg Seaborgium
Bh Bohrium
Hs Hassium
Mt Meitnerium
Ds Darmstadtium
Rg Roentgenium
Cn Copernicium
Nh Nihonium
Fl Flerovium
Mc Moscovium
Lv Livermorium
Ts Tennessine
Og Oganesson

{'Ac': 'Actinium',
 'Ag': 'Silver',
 'Al': 'Aluminum,',
 'Am': 'Americium',
 'Ar': 'Argon',
 'As': 'Arsenic',
 'At': 'Astatine',
 'Au': 'Gold',
 'B': 'Boron',
 'Ba': 'Barium',
 'Be': 'Beryllium',
 'Bh': 'Bohrium',
 'Bi': 'Bismuth',
 'Bk': 'Berkelium',
 'Br': 'Bromine',
 'C': 'Carbon',
 'Ca': 'Calcium',
 'Cd': 'Cadmium',
 'Ce': 'Cerium',
 'Cf': 'Californium',
 'Cl': 'Chlorine',
 'Cm': 'Curium',
 'Cn': 'Copernicium',
 'Co': 'Cobalt',
 'Cr': 'Chromium',
 'Cs': 'Cesium',
 'Cu': 'Copper',
 'Db': 'Dubnium',
 'Ds': 'Darmstadtium',
 'Dy': 'Dysprosium',
 'Er': 'Erbium',
 'Es': 'Einsteinium',
 'Eu': 'Europium',
 'F': 'Fluorine',
 'Fe': 'Iron',
 'Fl': 'Flerovium',
 'Fm': 'Fermium',
 'Fr': 'Francium',
 'Ga': 'Gallium',
 'Gd': 'Gadolinium',
 'Ge': 'Germanium',
 'H': 'Hydrogen',
 'He': 'Helium',
 'Hf': 'Hafnium',
 'Hg': 'Mercury',
 'Ho': 'Holmium',
 'Hs': 'Hassium',
 'I': 'Iodine',
 'In': 'Indium',
 'Ir': 'Iridium',
 'K': 'Potassium',
 'Kr': 'Krypton',
 'La': 'Lanthanum',
 'Li': 'Lithium',
 'Lr': 'Lawrencium',
 'Lu': 'Lutetium',
 'Lv': 'Livermorium',
 'Mc': 'Moscovium',
 'Md': 'Mendelevium',
 'Mg': 'Magnesium',
 'Mn': 'Manganese',
 'Mo': 'Molybdenum',
 'Mt': 'Meitnerium',
 'N': 'Nitrogen',
 'Na': 'Sodium',
 'Nb': 'Niobium',
 'Nd': 'Neodymium',
 'Ne': 'Neon',
 'Nh': 'Nihonium',
 'Ni': 'Nickel',
 'No': 'Nobelium',
 'Np': 'Neptunium',
 'O': 'Oxygen',
 'Og': 'Oganesson',
 'Os': 'Osmium',
 'P': 'Phosphorus',
 'Pa': 'Protactinium',
 'Pb': 'Lead',
 'Pd': 'Palladium',
 'Pm': 'Promethium',
 'Po': 'Polonium',
 'Pr': 'Praseodymium',
 'Pt': 'Platinum',
 'Pu': 'Plutonium',
 'Ra': 'Radium',
 'Rb': 'Rubidium',
 'Re': 'Rhenium',
 'Rf': 'Rutherfordium',
 'Rg': 'Roentgenium',
 'Rh': 'Rhodium',
 'Rn': 'Radon',
 'Ru': 'Ruthenium',
 'S': 'Sulfur',
 'Sb': 'Antimony',
 'Sc': 'Scandium',
 'Se': 'Selenium',
 'Sg': 'Seaborgium',
 'Si': 'Silicon',
 'Sm': 'Samarium',
 'Sn': 'Tin',
 'Sr': 'Strontium',
 'Ta': 'Tantalum',
 'Tb': 'Terbium',
 'Tc': 'Technetium',
 'Te': 'Tellurium',
 'Th': 'Thorium',
 'Ti': 'Titanium',
 'Tl': 'Thallium',
 'Tm': 'Thulium',
 'Ts': 'Tennessine',
 'U': 'Uranium',
 'V': 'Vanadium',
 'W': 'Tungsten',
 'Xe': 'Xenon',
 'Y': 'Yttrium',
 'Yb': 'Ytterbium',
 'Zn': 'Zinc',
 'Zr': 'Zirconium'}

In [42]:
with open("paraview_VESTA_atom.json", "w") as j:
    j.write('[\n\t{\n\t\t"Annotations" :\n\t\t[\n')
    for i in range(df_elm.shape[0]):
        mat = df_elm["mat"].loc[i]
        if mat == "D":
            annot = "Deuterium"
        elif mat == "XX":
            annot = "etc."
        else:
            annot = mat_annot[mat]
            
        j.write('\t\t\t"%s",\n\t\t\t"%s",\n' %(mat, annot))
    
    j.write('\t\t],\n\t\t"IndexedColors" :\n\t\t[\n')
    for i in range(df_elm.shape[0]):
        j.write('\t\t\t%s,\n' %(df_elm["R"].loc[i]))
        j.write('\t\t\t%s,\n' %(df_elm["G"].loc[i]))
        j.write('\t\t\t%s,\n' %(df_elm["B"].loc[i]))
        
    j.write('\t\t],\n\t\t"Name" : "VESTA atom"\n\t}\n]')